### ISSUE TITLE
server crash upon vein mine

### ISSUE THREAD

**Issue by huntzilla360c** [bloop428/Excavation#10]
[crash-2020-08-05_18.17.25-server.txt](https://github.com/bloop428/Excavation/files/5031565/crash-2020-08-05_18.17.25-server.txt)

vein mining, I was looking at soapstone(Oh the Biomes Youll Go), it says digital miner(Mekanism) in there but the digital miner is mining on a much lower elevation than where I was.

Edit- also i have vein mined hundreds of times prior

**Comment by huntzilla360c** [comment]
[crash-2020-08-05_20.11.48-server.txt](https://github.com/bloop428/Excavation/files/5031799/crash-2020-08-05_20.11.48-server.txt)
digital miner is mining from y= 6 to 0,   i vein mined some planks, at y= 84 and it was only about 8 blocks.

**Comment by bloop428** [comment]
Note to self for when i can deal with this: ForgeHooks.onBlockBreakEvent seems to be having issues with some kind of block

**Comment by bloop428** [comment]
@huntzilla360c Any chance you could try breaking soapstone again while the digital miner is off and see if the server crashes?

**Comment by huntzilla360c** [comment]
> @huntzilla360c Any chance you could try breaking soapstone again while the digital miner is off and see if the server crashes?

I was able to mine several types of blocks, another that crashed the server was XP ore, (not the expetrified ore in the modpack) in the first instance with the soapstone it broke and crashed, with the wood that only crashed the server, when it started again I was able to vein-mine that wood without it crashing... and then the same thing happened with the xp ore. (I'm at work till 6am (2am currently))
