### ISSUE TITLE
Crash when pressing ~

### ISSUE THREAD

**Issue by medtryx** [bloop428/Excavation#14]
With the latest release (excavation-1.4.jar) pressing ~ causes a crash. This happens even if your Excavate keybind is a different key.  Pressing whatever you have set as a keybind does not cause a crash, and does excavate as expected.   

Here is a [pastebin log](https://pastebin.com/DcFsN3KP) of the crash with only Forge and Excavation installed.

**Comment by bloop428** [comment]
This is strange. i just went into my dev environment and tested it and got this crash, but then i restarted after adding some logging and its no longer crashing.

**Comment by medtryx** [comment]
Again able to reproduce anytime I launch the game. [Attached is a Twitch Launcher crash log. ](https://pastebin.com/jym3ZRDq)

**Comment by bloop428** [comment]
Very strange. I’ll try installing the mod through twotch rather than using my dev environment and see if i can reproduce this. I’m currently very confused about what is happening with both of these bugs.

**Comment by bloop428** [comment]
turns out im an IDIOT and didnt update the gradle build script after i removed net. from my package path. AAAAAAAAAAA

**Comment by bloop428** [comment]
This should be fixed now. I had some typos and I kinda feel like an idiot
