### ISSUE TITLE
[1.16.1] Minor Compatibility issue with Silent Gear (Silent Gem's) tools

### ISSUE THREAD

**Issue by elowanut** [bloop428/Excavation#19]
**Forge**: forge-1.16.1-32.0.108
**Excavation:** excavation-1.5.1
**Other mods:** SilentGear-1.16.1-2.1.0+161

This is a compatibility issue between Excavation and Silent Gear. In short, if the excavation would fully deplete the tool, the tool breaks, despite the fact that Silent Gear tools are not supposed to be able to completely break (e.g. they turn into "broken" variants of themselves that can subsequently be repaired).

Excavation works normally otherwise.

**Comment by bloop428** [comment]
I should be able to tix this, but I’ll have to look imto how those tool’s handle going into their broken state so that I can correctly handle it. I’ll look into it tomorrow. Thanks for the report

**Comment by bloop428** [comment]
Fixed by 799205f
