### ISSUE TITLE
CTD: "Missing License Information"

### ISSUE THREAD

**Issue by AngleWyrm10** [bloop428/Excavation#22]
```-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[?:?] {re:classloading}
-- NO MOD INFO AVAILABLE --
Details:
	Mod File: NO FILE INFO
	Failure message: Missing License Information in file Mod File: C:\Games\MultiMC\instances\1.16.3\.minecraft\mods\excavation-1.5.2.jar
	Mod Version: NO MOD INFO AVAILABLE
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
```
———————————
Excavation v1.5.2
Minecraft v1.16.3
Forge v34.1.0

**Comment by AxionM** [comment]
I'm no mods creator or anything, but it seems to me that there is a line missing in the "\META-INF\mods.toml" file.
The line should be something like:  license="Something something"
I got the mod to load after adding the license-line.

**Comment by Failz13405** [comment]
Im having the same issue. You figure anything out?

**Comment by bloop428** [comment]
Hey! Sorry I've been away for so long, I'll fix this today.

**Comment by bloop428** [comment]
There are differences between 1.16.1 and 1.16.3. The mod in its current state is not compatible with 1.16.3. I will have to update it in the future

**Comment by LoverHZ** [comment]
Maybe you should try adding `license="MIT"` in the `mods.toml` file,or **other license**, and the `mods.toml` in `mod.jar/META-INF/`

**Comment by Gbergz** [comment]
> I will have to update it in the future.
Hey, any plans on updating to 1.16.5 in the near future? Miss this mod.
Thanks,
**-** Gbergz
