### ISSUE TITLE
1.17.1 version 

### ISSUE THREAD

**Issue by Magnic** [bloop428/Excavation#28]
On 1.17.1 version Forge 37.0.90 When you veinmine tall grass it changes whatever block you didn't hit into blue wool.
No other problems so far.

**Comment by bloop428** [comment]
LMAO. I accidentily left in so much bug testing stuff I'm sorry. Fixing now!

**Comment by bloop428** [comment]
Fixed in version 1.6.2. Uploading ASAP. I do not think curseforge accepts mods on weekends so here is a direct download: https://drive.google.com/file/d/1JgurqpgqzmVxee5lNmCkxTHRPMT37qsG/view?usp=sharing
