### ISSUE TITLE
Cannot edit config 1.16

### ISSUE THREAD

**Issue by Leogendra** [bloop428/Excavation#29]
Hello, I've installed your mod on my 1.16.5 server, it works perfectly fine !

The thing is, I couldn't find a way to modify the "excavation-common.toml" file on my server (aternos)

in fact, I want to add the whitelist settings with the following settings

   "Invert Block Blacklist" = true

   "Block Blacklist" = ["minecraft:birch_log"]

but everytime I launch the server it reset the configuration and the file (the only things left are the "base" settings that i've changed)

idk if this is Aternos or if i use the wrong file format ;

i've tried to put the settings in [common], [client] or [server] but that doesn't change anything...

**Comment by bloop428** [comment]
You are adding the blacklist as a block tag in a datapack, correct? It is not a config option.

**Comment by bloop428** [comment]
![image](https://user-images.githubusercontent.com/6138413/143488006-8f112b77-433c-4951-ab65-e17fc88cf4cd.png)
Works for me.

**Comment by Leogendra** [comment]
hum okay,
btw, where the infos are located ? I couldn't find any doc or watever on how I can use the config/datapack files in the readme or idk
Is there a text document with all the infos ?

**Comment by bloop428** [comment]
It is just a regular vanilla datapack. Minecraft wiki has information.
