### ISSUE TITLE
[Suggestion] Add groups to allow excavating two types at once. Example in description.

### ISSUE THREAD

**Issue by Gbergz** [bloop428/Excavation#3]
Title^

Example:
``    [
      "minecraft:cobblestone",
      "minecraft:infested_cobblestone"
    ],``

When mined those 2 will get excavated together. Hope you understand what I mean. 

Useful when for example when playing with a Dense Ore mod or something similar. 
Another example would be adding a Dense Coal Ore together with normal Coal Ore will allow both to be excavated.

Also while I'm at it herer is it possible to also add an option to prevent excavating with only hand. So only excavating with an item in hand works. ^

**-** Gbergz

**Comment by bloop428** [comment]
I'm still unsure if I want to add this. I'll leave it open for now, though

**Comment by Gbergz** [comment]
Would be super handy for modpack creators like myself. But you do you :)

**Comment by bloop428** [comment]
I'm working on adding this. Can't release it until monday though because curse doesnt accept file uploads on weekends

**Comment by Gbergz** [comment]
Glad to hear it's coming along! And no problem. 👍

**Comment by bloop428** [comment]
Working on the group check right now. Hoping to have this out by tonight.
