### ISSUE TITLE
[1.18.1] Hunger doesn't drain if Vacuum config is set to False.

### ISSUE THREAD

**Issue by Gbergz** [bloop428/Excavation#31]
Hunger doesn't drain if Vacuum config is set to False. (Exhaustion is set to 52).

Minecraft: 1.18.1
Forge: 39.0.9
Excavation: 1.7 | https://www.curseforge.com/minecraft/mc-mods/excavation/files/3577283

**-** Gbergz

**Comment by bloop428** [comment]
Just checking you confirmed it works while vacuum is true?
