### ISSUE TITLE
[1.16.1] Item in hand disappears when attempting to excavate. Excavate doesn't seem to work.

### ISSUE THREAD

**Issue by Gbergz** [bloop428/Excavation#5]
Title^

**Minecraft:** 1.16.1
**Forge:** 32.0.88
**Mod-Version:** [1.3](https://www.curseforge.com/minecraft/mc-mods/excavation/files/3023529)

GIF Showing the issue:
https://gyazo.com/11f9c9e77a3850acf3ff8c8781bd2430

EDIT: Also, thanks for the quick updates on the suggestions. :)

**Comment by bloop428** [comment]
OMG HAHAHAHA This is the tool break logic firing on any item. I'll fix this right now

**Comment by bloop428** [comment]
Uploading to curse rn
