### ISSUE TITLE
[1.16.1] Some blocks can't be excavated while others can, some ores for example.

### ISSUE THREAD

**Issue by Gbergz** [bloop428/Excavation#8]
Title^

Currently I can't Excavate Vanilla Ores and some other building blocks.

**Example:**
https://gyazo.com/defff79bdfc5b7c5fc6a512f9734d28d

**Minecraft:** 1.16.1
**Forge:** 32.0.88
**Mod-Version:** 1.3.b

**Comment by Gbergz** [comment]
Hm, after a restart it appears they are able to be excavated again.

**Comment by bloop428** [comment]
Just to confirm, you were holding down the excavate keybind when you broke each block in that video? Also, about how long were you in the world and how much did you use the excavation before it stopped working?

**Comment by Gbergz** [comment]
Yes I was holding down the excavate button on each block break. 
And I don't know how long, at least less than 5 minutes. I just was flying around the world testing stuff and then it stops working randomly. And when it does stop working it **_only_** works when I bring out the correct tool for the job. Not like before when I could use the hand to excavate anything.

**Comment by bloop428** [comment]
SO! Turns out this is an issue only in creative mode where all of the blocks you couldnt mine can't be mined with a player's fist if they were in survival. I will add a line to ignore this check if the player is in creative.
