### ISSUE TITLE
[1.16.1] Tools take damage when excavating while in Creative Mode.

### ISSUE THREAD

**Issue by Gbergz** [bloop428/Excavation#9]
Title^ 

**Minecraft:** 1.16.1
**Forge:** 32.0.88
**Mod-Version:** 1.3.b

**Video of it:**
https://gyazo.com/132c79551b3b82ca2cd0f8a387d847ef

**Comment by bloop428** [comment]
This should be an easy fix. I’m not sure if i can work on the mod for a few days though. Minor issue, shouldn’t break much
